### ISSUE TITLE
"npm install failed with code 1" when Packing external modules

### ISSUE THREAD

**Issue by andreasgrimm** [floydspace/serverless-esbuild#160]
Before using serverless-esbuild the installation of private packages from a private GitHub npm registry was possible without any errors.

Only when trying to use `serverless-esbuild@1.16.0` (while using `serverless@2.50.0`) with an external package that resides in a private npm registry the step `Packing external modules: @myregistry/mymodule` results in

```
Error: npm install failed with code 1
--
96 | at ChildProcess.<anonymous> (.../node_modules/serverless-esbuild/dist/utils.js:48:24)
97 | at ChildProcess.emit (events.js:311:20)
98 | at ChildProcess.EventEmitter.emit (domain.js:482:12)
99 | at maybeClose (internal/child_process.js:1021:16)
100 | at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

Any clue on how to specify which exact `.npmrc` it is using or whow to get deeper insights regarding the error?

On a second thought (and please excuse me for not being that deep into the topic yet): Is it ultimately needed to temporarily "npm install" the external packages again (into folder `.esbuild/.build`) or can't they just be reused from the project root's `node_modules` folder?

**Comment by andreasgrimm** [comment]
Turned out the .npmrc in use was missing some information.
