### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gparonitti** [floydspace/serverless-esbuild#286]
Hi there,
I receive the `TypeError:  Cannot convert undefined or null to object` on version `1.25.0` of your plugin, 'till version `1.24.1` it has been working seamlessly. My esbuild configuration is
```
    esbuild: {
      minify: false,
      bundle: true,
      sourcemap: offline,
      keepNames: true,
      logLevel: 'debug',
      legalComments: 'none',
      ...(offline && { nodePaths }),
      // if not offline don't bundle the layer package otherwise bundle them but aws-crt
      ...((!offline && { external }) || { external: ['aws-crt'] })
    }
```
```
Environment: darwin, node 17.4.0, framework 3.5.1 (local), plugin 6.1.3, SDK 4.3.2
```

the error stack is:
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at convertTrees (.../node_modules/serverless-esbuild/dist/packagers/npm.js:85:27)
    at NPM.getProdDependencies (.../node_modules/serverless-esbuild/dist/packagers/npm.js:141:27)
    at async EsbuildServerlessPlugin.pack (.../node_modules/serverless-esbuild/dist/pack.js:125:11)
    at async before:package:createDeploymentArtifacts (.../node_modules/serverless-esbuild/dist/index.js:83:17)
    at async PluginManager.runHooks (.../node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (.../node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.spawn (.../node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (.../node_modules/serverless/lib/plugins/deploy.js:40:11)
    at async PluginManager.runHooks (.../node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (.../node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (.../node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (.../node_modules/serverless/lib/serverless.js:174:5)
    at async .../node_modules/serverless/scripts/serverless.js:687:9
```

I would like to maintain your package updated. Cheers!

**Comment by samchungy** [comment]
Hello! Thank you for the report. This was my change as part of a larger refactor of the dependency detection. It looks like there's some other edge case that I didn't consider.

It looks like your `parsedDeps`. It looks like your `parsedDeps` depenedencies object is empty which is strange. If you are running this locally could you sneak in a console log for me before line 140? `node_modules/serverless-esbuild/dist/packagers/npm.js:141` cheers!

eg.

![image](https://user-images.githubusercontent.com/18017094/156261299-66d5ee26-8829-4a26-9965-c7afebeb15cc.png)

**Comment by gparonitti** [comment]
it works if I change:

```
const convertTrees = (currentTree, rootDeps, currentDeps = rootDeps) => {
            return Object.entries(currentTree).reduce((deps, [name, tree]) => {
...
```
to
```
const convertTrees = (currentTree, rootDeps, currentDeps = rootDeps) => {
            return !currentTree ? {} : Object.entries(currentTree).reduce((deps, [name, tree]) => {
```

But maybe there are other side effects I can't foreseen.
PS. I accidentally close the issue :)

**Comment by samchungy** [comment]
Thank you! The change I made was based on no existing unit tests so thank you for that! Much appreciated!
