### ISSUE TITLE
ModuleNotFound error when attempting to invoke python function via API gateway

### ISSUE THREAD

**Issue by davidworkman9** [floydspace/serverless-esbuild#357]
Reproduction: https://github.com/davidworkman9/sls-esbuild-repro

```
ANY /func_py (λ: func_py)
Traceback (most recent call last):
  File "/Users/dave/sls-esbuild-repro/node_modules/serverless-offline/dist/lambda/handler-runner/python-runner/invoke.py", line 76, in <module>

    module = import_module(args.handler_path.replace(os.sep, '.'))
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myesbuild.mybuild.func_py'
```

**Comment by samchungy** [comment]
You may need to use package patterns to reference said python handler. This is because we actually ignore python handlers so it should fallback to default Serverless packaging

**Comment by davidworkman9** [comment]
Thanks @samchungy that did the trick.
