### ISSUE TITLE
TypeError: this.consoleLog is not a function

### ISSUE THREAD

**Issue by rafcremer** [floydspace/serverless-esbuild#371]
**Describe the bug**
When running `sls offline` I get:
```
Serverless: Invoke offline:start
 
  Type Error ---------------------------------------------
 
  TypeError: this.consoleLog is not a function
      at Object.log (/Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/lib/classes/CLI.js:414:10)
      at EsbuildServerlessPlugin.bundle (/Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless-esbuild/dist/bundle.js:16:14)
      at Object.before:offline:start:init [as hook] (/Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless-esbuild/dist/index.js:62:28)
      at /Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/lib/classes/PluginManager.js:498:55
  From previous event:
      at PluginManager.invoke (/Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at /Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/lib/classes/PluginManager.js:533:24
  From previous event:
      at PluginManager.run (/Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/lib/classes/PluginManager.js:533:8)
      at /Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/lib/Serverless.js:162:33
  From previous event:
      at Serverless.run (/Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/lib/Serverless.js:149:74)
      at /Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/scripts/serverless.js:58:26
      at processImmediate (internal/timers.js:464:21)
  From previous event:
      at Object.<anonymous> (/Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/scripts/serverless.js:58:4)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:14)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at Object.<anonymous> (/Users/rafael/GitHub/hazardco_api_serverless/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.3
     Framework Version:         1.83.3 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

No additional custom esbuild added to the serverles.yml

Thanks!

**To Reproduce**
`sls offline start --useSeparateProcesses --noTimeout --stage dev`

**Versions (please complete the following information):**
 - OS: Mac
 - Serverless Framework Version:
 ```
 Framework Core: 1.80.0
 Plugin: 3.8.4
 SDK: 2.3.2
 Components: 2.34.9
```
 - Plugin Version: 
 ```
 "esbuild": "^0.15.7",
 "serverless-prune-plugin": "^1.4.2",
 ```

**Additional context**

**Comment by floydspace** [comment]
Fixed in [v1.32.9](https://github.com/floydspace/serverless-esbuild/releases/tag/v1.32.9)
