### ISSUE TITLE
Error: Invalid option: "exclude"

### ISSUE THREAD

**Issue by bryantbiggs** [floydspace/serverless-esbuild#78]
When using the latest version of the plugin with the latest of esbuild, the following error is encountered:

```bash 
$ sls deploy -v
Serverless: Auto instrumenting functions with Datadog
Serverless: Adding Lambda Layers to functions
Serverless: Compiling with esbuild...
 
  Error --------------------------------------------------
 
  Error: Invalid option: "exclude"
      at checkForInvalidFlags (/home/bryantbiggs/Documents/dogged-params/node_modules/esbuild/lib/main.js:226:13)
      at flagsForBuildOptions (/home/bryantbiggs/Documents/dogged-params/node_modules/esbuild/lib/main.js:312:3)
      at Object.build (/home/bryantbiggs/Documents/dogged-params/node_modules/esbuild/lib/main.js:469:49)
      at /home/bryantbiggs/Documents/dogged-params/node_modules/esbuild/lib/main.js:703:67
      at new Promise (<anonymous>)
      at Object.build (/home/bryantbiggs/Documents/dogged-params/node_modules/esbuild/lib/main.js:703:26)
      at /home/bryantbiggs/Documents/dogged-params/node_modules/esbuild/lib/main.js:629:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 0)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

This is resolved by downgrading to v1.4.0 or by setting the esbuild version to be `~0.6.0` (0.6.34). It looks like somewhere in v0.7.x of esbuild this plugin stopped working with the excludes option

I have a repro [here](https://github.com/clowdhaus/dogged-params/pull/2)

**Comment by floydspace** [comment]
@bryantbiggs thank you for your report. indeed, it was breaking change in esbuild v0.7
